/* DELETE 'cinemaDB' database*/
DROP SCHEMA IF EXISTS cinemaDB;
/* DELETE USER 'spq' AT LOCAL SERVER*/
DROP USER IF EXISTS 'spq'@'%';



/* CREATE 'cinemaDB' DATABASE */
CREATE SCHEMA cinemaDB;
/* CREATE THE USER 'spq' AT LOCAL SERVER WITH PASSWORD 'spq' */
CREATE USER IF NOT EXISTS 'spq'@'%' IDENTIFIED BY 'spq';
/* GRANT FULL ACCESS TO THE DATABASE FOR THE USER 'spq' AT LOCAL SERVER*/
GRANT ALL ON cinemaDB.* TO 'spq'@'%';

